[package]
name = "handler"
version = "0.1.0"
authors = ["suhail muhammed <smuham31@uic.edu"]
edition = "2018"

[dependencies]
nix = "*"
signal-hook = { version = "0.3.13", features = ["extended-siginfo"] }
libc = "*"
helper = { path = "../helper" }